version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=mojex
      - POSTGRES_PASSWORD=admin1234
    ports:
      - '5432:5432' 
    volumes:
      - ./data/postgres:/var/lib/postgresql/data